version: "3.8"

services:

  hailodfc-docker:
    image: localhost:5000/local/hailodfc-docker:debian-latest
    pull_policy: "missing"
    container_name: hailodfc-docker
    env_file:
      - .env
    environment:
      - "ENABLE_INFINITE_LOOP=true"
    volumes:
      - ./models:/models
    restart: "unless-stopped"
    # Needed to redirect log
    privileged: true
    networks:
      - podman

networks:
  podman:
    external: true
